name: Setup
description: Setup for project workflows
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version-file: .python-version
